server:
  port: 2023

spring:
  datasource:
    password: ajt8IvPc2xeAebegwV4kBiBRs6nBd57B
    username: zisrxbjk
    url: jdbc:postgresql://mahmud.db.elephantsql.com:5432/zisrxbjk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect6
  flyway:
    default-schema: public
    create-schemas: false
    enabled: true
    baseline-on-migrate: false
  sql:
    init:
      encoding: UTF-8

logging:
  level:
    root: info
