server:
  port: 2024

cloud:
  aws:
    credentials:
      access-key: AKIAU5JHNIYVZI6YZ55G
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: clinic-storage

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    password: 15082003
    username: postgres
    url: jdbc:postgresql://localhost:5432/clinic
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    default-schema: public
    create-schemas: false
    enabled: true
    baseline-on-migrate: false
  sql:
    init:
      encoding: UTF-8

logging:
  level:
    root: info